version: '3'
services:
  dbpostgresql_accounts:
    container_name: "accounts_db"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: accountsDb
